/**
 * Material library — seed data.
 *
 * Realistic Australian metal-fab inventory: a mix of mild steel, stainless,
 * aluminium, in the forms a sheet-metal / structural shop typically stocks.
 */

import type { Material } from './types';

const NOW = '2026-04-07T09:00:00Z';

export const MATERIAL_SEED: Material[] = [
  {
    id: 'mat-ms-sheet-1.6',
    name: 'Mild Steel Sheet 1.6mm',
    code: 'MS-SHT-1.6',
    type: 'sheet',
    grade: '250MPa',
    densityKgM3: 7850,
    cost: { unit: 'per_kg', amount: 2.4, currency: 'AUD' },
    stockSizes: [
      { width: 1200, length: 2400, thickness: 1.6 },
      { width: 1500, length: 3000, thickness: 1.6 },
    ],
    thicknesses: [1.6],
    compatibleFinishes: ['fin-pc-black', 'fin-galv', 'fin-paint-2k'],
    suppliers: [
      { name: 'Hunter Steel Co', leadTimeDays: 3 },
      { name: 'Pacific Metals', leadTimeDays: 5 },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-ms-sheet-2.0',
    name: 'Mild Steel Sheet 2.0mm',
    code: 'MS-SHT-2.0',
    type: 'sheet',
    grade: '250MPa',
    densityKgM3: 7850,
    cost: { unit: 'per_kg', amount: 2.35, currency: 'AUD' },
    stockSizes: [
      { width: 1200, length: 2400, thickness: 2.0 },
      { width: 1500, length: 3000, thickness: 2.0 },
    ],
    thicknesses: [2.0],
    compatibleFinishes: ['fin-pc-black', 'fin-galv', 'fin-paint-2k'],
    suppliers: [{ name: 'Hunter Steel Co', leadTimeDays: 3 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-ss304-sheet-1.5',
    name: 'Stainless 304 Sheet 1.5mm 2B',
    code: 'SS304-SHT-1.5',
    type: 'sheet',
    grade: '304',
    densityKgM3: 8000,
    cost: { unit: 'per_kg', amount: 11.8, currency: 'AUD' },
    stockSizes: [
      { width: 1219, length: 2438, thickness: 1.5 },
      { width: 1500, length: 3000, thickness: 1.5 },
    ],
    thicknesses: [1.5],
    compatibleFinishes: ['fin-polish-no4', 'fin-passivate'],
    suppliers: [{ name: 'Pacific Metals', leadTimeDays: 5 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-al5052-sheet-2.0',
    name: 'Aluminium 5052 Sheet 2.0mm',
    code: 'AL5052-SHT-2.0',
    type: 'sheet',
    grade: '5052-H32',
    densityKgM3: 2680,
    cost: { unit: 'per_kg', amount: 9.2, currency: 'AUD' },
    stockSizes: [
      { width: 1200, length: 2400, thickness: 2.0 },
      { width: 1500, length: 3000, thickness: 2.0 },
    ],
    thicknesses: [2.0],
    compatibleFinishes: ['fin-anodise-clear', 'fin-pc-black'],
    suppliers: [{ name: 'Pacific Metals', leadTimeDays: 5 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-rhs-50x50x3',
    name: 'RHS 50×50×3 Mild Steel',
    code: 'RHS-50-50-3',
    type: 'rhs',
    grade: '350MPa',
    densityKgM3: 7850,
    cost: { unit: 'per_m', amount: 14.5, currency: 'AUD' },
    stockSizes: [
      { length: 6000, profile: '50x50x3' },
      { length: 8000, profile: '50x50x3' },
    ],
    thicknesses: [3.0],
    compatibleFinishes: ['fin-pc-black', 'fin-galv'],
    suppliers: [{ name: 'Hunter Steel Co', leadTimeDays: 4 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-shs-25x25x2',
    name: 'SHS 25×25×2 Mild Steel',
    code: 'SHS-25-25-2',
    type: 'shs',
    grade: '350MPa',
    densityKgM3: 7850,
    cost: { unit: 'per_m', amount: 6.8, currency: 'AUD' },
    stockSizes: [{ length: 6000, profile: '25x25x2' }],
    thicknesses: [2.0],
    compatibleFinishes: ['fin-pc-black', 'fin-galv'],
    suppliers: [{ name: 'Hunter Steel Co', leadTimeDays: 4 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-angle-40x40x3',
    name: 'Angle 40×40×3 Mild Steel',
    code: 'ANG-40-40-3',
    type: 'angle',
    grade: '300MPa',
    densityKgM3: 7850,
    cost: { unit: 'per_m', amount: 7.2, currency: 'AUD' },
    stockSizes: [{ length: 6000, profile: '40x40x3' }],
    thicknesses: [3.0],
    compatibleFinishes: ['fin-pc-black', 'fin-galv', 'fin-paint-2k'],
    suppliers: [{ name: 'Hunter Steel Co', leadTimeDays: 4 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mat-flat-25x6',
    name: 'Flat Bar 25×6 Mild Steel',
    code: 'FLT-25-6',
    type: 'flat_bar',
    grade: '300MPa',
    densityKgM3: 7850,
    cost: { unit: 'per_m', amount: 4.5, currency: 'AUD' },
    stockSizes: [{ length: 6000, profile: '25x6' }],
    thicknesses: [6.0],
    compatibleFinishes: ['fin-pc-black', 'fin-galv'],
    suppliers: [{ name: 'Hunter Steel Co', leadTimeDays: 4 }],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
