/**
 * Finish library — seed data.
 *
 * A realistic Australian metal-fab finishes catalogue: powdercoat, hot-dip galv,
 * 2-pack paint, anodise, polish, passivate. Mix of in-house and subcontract
 * sources to exercise the shipping/lead-time fields.
 */

import type { Finish } from './types';

const NOW = '2026-04-07T09:00:00Z';

export const FINISH_SEED: Finish[] = [
  {
    id: 'fin-pc-black',
    name: 'Powder Coat — Jet Black',
    code: 'PC-BLK',
    type: 'powder_coat',
    costPerM2: 22,
    flatFee: 0,
    setupCost: 80,
    leadTimeDays: 5,
    colour: { ral: 'RAL 9005', name: 'Jet Black' },
    compatibleMaterials: ['mat-ms-sheet-1.6', 'mat-ms-sheet-2.0', 'mat-rhs-50x50x3', 'mat-shs-25x25x2', 'mat-angle-40x40x3', 'mat-flat-25x6', 'mat-al5052-sheet-2.0'],
    source: 'subcontract',
    subcontractor: { name: 'Brisbane Powdercoaters', contact: 'orders@bnepc.com.au' },
    shipping: { fixed: 45, perKg: 0.4, perKm: 0 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fin-pc-white',
    name: 'Powder Coat — Pure White',
    code: 'PC-WHT',
    type: 'powder_coat',
    costPerM2: 22,
    flatFee: 0,
    setupCost: 80,
    leadTimeDays: 5,
    colour: { ral: 'RAL 9010', name: 'Pure White' },
    compatibleMaterials: ['mat-ms-sheet-1.6', 'mat-ms-sheet-2.0', 'mat-al5052-sheet-2.0'],
    source: 'subcontract',
    subcontractor: { name: 'Brisbane Powdercoaters', contact: 'orders@bnepc.com.au' },
    shipping: { fixed: 45, perKg: 0.4, perKm: 0 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fin-galv',
    name: 'Hot-Dip Galvanise',
    code: 'HDG',
    type: 'galv',
    costPerM2: 18,
    flatFee: 60,
    setupCost: 120,
    leadTimeDays: 7,
    colour: null,
    compatibleMaterials: ['mat-ms-sheet-1.6', 'mat-ms-sheet-2.0', 'mat-rhs-50x50x3', 'mat-shs-25x25x2', 'mat-angle-40x40x3', 'mat-flat-25x6'],
    source: 'subcontract',
    subcontractor: { name: 'Industrial Galvanisers', contact: 'jobs@indgalv.com.au' },
    shipping: { fixed: 95, perKg: 0.25, perKm: 0 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fin-paint-2k',
    name: '2-Pack Paint — Custom Colour',
    code: '2K-PAINT',
    type: 'paint',
    costPerM2: 38,
    flatFee: 0,
    setupCost: 150,
    leadTimeDays: 4,
    colour: { ral: 'CUSTOM', name: 'Customer-specified' },
    compatibleMaterials: ['mat-ms-sheet-1.6', 'mat-ms-sheet-2.0', 'mat-angle-40x40x3'],
    source: 'in_house',
    subcontractor: null,
    shipping: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fin-anodise-clear',
    name: 'Anodise — Clear',
    code: 'ANO-CLR',
    type: 'anodise',
    costPerM2: 32,
    flatFee: 0,
    setupCost: 100,
    leadTimeDays: 6,
    colour: { ral: 'NONE', name: 'Clear' },
    compatibleMaterials: ['mat-al5052-sheet-2.0'],
    source: 'subcontract',
    subcontractor: { name: 'Anodising Australia', contact: 'sales@anoaus.com.au' },
    shipping: { fixed: 65, perKg: 0.35, perKm: 0 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fin-polish-no4',
    name: 'Stainless Polish — #4 Brushed',
    code: 'POL-N4',
    type: 'polish',
    costPerM2: 45,
    flatFee: 0,
    setupCost: 90,
    leadTimeDays: 3,
    colour: null,
    compatibleMaterials: ['mat-ss304-sheet-1.5'],
    source: 'in_house',
    subcontractor: null,
    shipping: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fin-passivate',
    name: 'Stainless Passivate',
    code: 'PASS',
    type: 'passivate',
    costPerM2: 12,
    flatFee: 0,
    setupCost: 60,
    leadTimeDays: 2,
    colour: null,
    compatibleMaterials: ['mat-ss304-sheet-1.5'],
    source: 'in_house',
    subcontractor: null,
    shipping: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
];
