import type { Machine } from './types';

export const MACHINE_GRID_MOCKS: Machine[] = [
  {
    id: 'mach-001',
    name: 'Laser Cutter #1',
    stationGroup: 'Cutting',
    status: 'running',
    cycleTimeLabel: '3:20 target',
    currentJob: {
      id: 'wo-005',
      woNumber: 'WO-2026-0005',
      moNumber: 'MO-2026-0002',
      productName: 'Server Rack Chassis',
      operation: 'Laser cut chassis panels',
      customerName: 'Pacific Fabrication',
      status: 'in_progress',
      estimatedMinutes: 30,
      actualMinutes: 9,
      unitsCompleted: 0,
      totalUnits: 2,
      executionState: 'inspect',
      revisionRequiresAck: false,
      dueDate: '2026-04-15',
    },
    nextJob: {
      id: 'wo-007',
      woNumber: 'WO-2026-0007',
      moNumber: 'MO-2026-0006',
      productName: 'Access Hatch Set',
      operation: 'Laser cut hatch blanks',
      customerName: 'Alliance Metal',
      status: 'pending',
      estimatedMinutes: 90,
      actualMinutes: 0,
      unitsCompleted: 0,
      totalUnits: 24,
      dueDate: '2026-04-16',
    },
  },
  {
    id: 'mach-002',
    name: 'Press Brake #2',
    stationGroup: 'Forming',
    status: 'idle',
    cycleTimeLabel: '2:00 target',
    nextJob: {
      id: 'wo-002',
      woNumber: 'WO-2026-0002',
      moNumber: 'MO-2026-0001',
      productName: 'Mounting Bracket Assembly',
      operation: 'Bend to spec',
      customerName: 'TechCorp Industries',
      status: 'pending',
      estimatedMinutes: 24,
      actualMinutes: 0,
      unitsCompleted: 0,
      totalUnits: 2,
      executionState: 'setup',
      revisionRequiresAck: true,
      dueDate: '2026-04-15',
    },
  },
  {
    id: 'mach-003',
    name: 'Welding Station A',
    stationGroup: 'Welding',
    status: 'blocked',
    cycleTimeLabel: '4:40 target',
    blockingIssue: 'First-off weld angle needs supervisor sign-off.',
    currentJob: {
      id: 'wo-003',
      woNumber: 'WO-2026-0003',
      moNumber: 'MO-2026-0001',
      productName: 'Mounting Bracket Assembly',
      operation: 'MIG weld assembly',
      customerName: 'TechCorp Industries',
      status: 'blocked',
      estimatedMinutes: 36,
      actualMinutes: 18,
      unitsCompleted: 0,
      totalUnits: 2,
      executionState: 'blocked',
      dueDate: '2026-04-15',
    },
    nextJob: {
      id: 'wo-009',
      woNumber: 'WO-2026-0009',
      moNumber: 'MO-2026-0007',
      productName: 'Fixture Frame Weldment',
      operation: 'Weld frame and tack gussets',
      customerName: 'Hunter Steel Co',
      status: 'pending',
      estimatedMinutes: 130,
      actualMinutes: 0,
      unitsCompleted: 0,
      totalUnits: 36,
      dueDate: '2026-04-17',
    },
  },
  {
    id: 'mach-004',
    name: 'CNC Mill #3',
    stationGroup: 'Machining',
    status: 'setup',
    cycleTimeLabel: '2:30 target',
    currentJob: {
      id: 'wo-006',
      woNumber: 'WO-2026-0006',
      moNumber: 'MO-2026-0002',
      productName: 'Server Rack Chassis',
      operation: 'CNC machine mounting holes',
      customerName: 'Pacific Fabrication',
      status: 'pending',
      estimatedMinutes: 28,
      actualMinutes: 4,
      unitsCompleted: 0,
      totalUnits: 2,
      executionState: 'setup',
      revisionRequiresAck: false,
      dueDate: '2026-04-15',
    },
    nextJob: {
      id: 'wo-010',
      woNumber: 'WO-2026-0010',
      moNumber: 'MO-2026-0008',
      productName: 'Control Plate Set',
      operation: 'Mill slots and countersinks',
      customerName: 'Kemppi Australia',
      status: 'pending',
      estimatedMinutes: 110,
      actualMinutes: 0,
      unitsCompleted: 0,
      totalUnits: 32,
      dueDate: '2026-04-18',
    },
  },
  {
    id: 'mach-005',
    name: 'Powder Coat Line',
    stationGroup: 'Finishing',
    status: 'idle',
    cycleTimeLabel: '3:50 target',
    overdue: true,
    nextJob: {
      id: 'wo-004',
      woNumber: 'WO-2026-0004',
      moNumber: 'MO-2026-0001',
      productName: 'Mounting Bracket Assembly',
      operation: 'Powder coat satin black',
      customerName: 'TechCorp Industries',
      status: 'pending',
      estimatedMinutes: 18,
      actualMinutes: 0,
      unitsCompleted: 0,
      totalUnits: 2,
      executionState: 'setup',
      revisionRequiresAck: false,
      dueDate: '2026-04-13',
    },
  },
  {
    id: 'mach-006',
    name: 'Laser Cutter #2',
    stationGroup: 'Cutting',
    status: 'running',
    cycleTimeLabel: '3:05 target',
    currentJob: {
      id: 'wo-011',
      woNumber: 'WO-2026-0011',
      moNumber: 'MO-2026-0009',
      productName: 'Battery Tray Blank Set',
      operation: 'Laser cut tray blanks',
      customerName: 'Sydney Rail Corp',
      status: 'in_progress',
      estimatedMinutes: 26,
      actualMinutes: 14,
      unitsCompleted: 1,
      totalUnits: 2,
      executionState: 'run',
      revisionRequiresAck: false,
      dueDate: '2026-04-16',
    },
    nextJob: {
      id: 'wo-012',
      woNumber: 'WO-2026-0012',
      moNumber: 'MO-2026-0010',
      productName: 'Guard Panel Nest',
      operation: 'Laser cut guard panels',
      customerName: 'Alliance Metal',
      status: 'pending',
      estimatedMinutes: 95,
      actualMinutes: 0,
      unitsCompleted: 0,
      totalUnits: 28,
      dueDate: '2026-04-18',
    },
  },
];
